version: '3'

networks:
  highload-network:
    driver: bridge

services:

        laravel:
            container_name: laravel
            build:
                context: ./php-fpm
                args:
                    - timezone=${TZ}
            networks:
                - highload-network
            ports:
                - "9001:9000"
            volumes:
                - ./../laravel:/laravel:rw,cached
                - laravel_log:/laravel/var/log
            env_file:
                - .env
            depends_on:
                - redis
                - memcached
                - db-master
                - db-slave-1
                - db-slave-2

        lara1:
            container_name: lara1
            build:
                context: ./php-fpm
                args:
                    - timezone=${TZ}
            networks:
                - highload-network
            ports:
                - "9002:9000"
            volumes:
                - ./../laravel:/laravel:rw,cached
                - laravel_log:/laravel/var/log
            env_file:
                - .env
            depends_on:
                - redis
                - memcached
                - db-master
                - db-slave-1
                - db-slave-2

        lara2:
            container_name: lara2
            build:
                context: ./php-fpm
                args:
                    - timezone=${TZ}
            networks:
                - highload-network
            ports:
                - "9003:9000"
            volumes:
                - ./../laravel:/laravel:rw,cached
                - laravel_log:/laravel/var/log
            env_file:
                - .env
            depends_on:
                - redis
                - memcached
                - db-master
                - db-slave-1
                - db-slave-2

        symfony:
            container_name: symfony
            build:
                context: ./php-fpm-symfony
                args:
                    - timezone=${TZ}
            networks:
                - highload-network
            ports:
                - "9004:9000"
            volumes:
                - ./../symfony:/symfony:rw,cached
                - symfony_log:/symfony/var/log
            env_file:
                - .env
            depends_on:
                - redis
                - memcached
                - db-master
                - db-slave-1
                - db-slave-2

        nginx:
            container_name: nginx
            build:
                context: ./nginx
                args:
                    - timezone=${TZ}
            ports:
                - "81:80"
                - "443:443"
            networks:
                - highload-network
            depends_on:
                - laravel
                - symfony
            volumes:
                - ./../laravel/public:/laravel/public
                - ./../lara1/public:/lara1/public
                - ./../lara2/public:/lara2/public
                - ./../symfony/public:/symfony/public
                - ./nginx/ssl:/etc/nginx/ssl
                - ./nginx/conf.d:/etc/nginx/conf.d
                - ./nginx/nginx_log:/var/log/nginx
                - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            env_file:
                - .env
            command: /bin/bash -c "exec nginx -g 'daemon off;'"

        redis:
            container_name: redis
            image: redis:latest
            ports:
                - "6379:6379"
            networks:
                - highload-network

        memcached:
            container_name: memcached
            image: memcached:latest
            ports:
                    - "11211:11211"
            networks:
                - highload-network

        db-master:
            container_name: db-master
            image: mysql:latest
            env_file:
                - ./db/master/.env.master
            ports:
                - "3307:3306"
            volumes:
                - ./db/master/master.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/master/mysql.master.cnf:/etc/mysql/conf.d/mysql.master.cnf
                - ./db/master/.data/mysql:/var/lib/mysql:rw
            networks:
                - highload-network

        db-slave-1:
            container_name: db-slave-1
            image: mysql:latest
            env_file:
                - db/slaves/slave_1/.env.slave
            depends_on:
                -  db-master
            ports:
                - "4406:3306"
            volumes:
                - ./db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/slaves/slave_1/mysql.slave.cnf:/etc/mysql/conf.d/mysql.slave.cnf
                - ./db/slaves/slave_1/.data/mysql:/var/lib/mysql:rw
            networks:
                - highload-network

        db-slave-2:
            container_name: db-slave-2
            image: mysql:latest
            env_file:
                - db/slaves/slave_2/.env.slave
            depends_on:
                - db-master
            ports:
                - "5506:3306"
            volumes:
                - ./db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/slaves/slave_2/mysql.slave.cnf:/etc/mysql/conf.d/mysql.slave.cnf
                - ./db/slaves/slave_2/.data/mysql:/var/lib/mysql:rw
            networks:
                - highload-network

        rabbit:
            container_name: rabbitMQ
            build: ./rabbitMQ
            networks:
                - highload-network
            ports:
                - "5672:5672"
                - "15672:15672"
            volumes:
                - ./rabbitMQ/data/mnesia:/var/lib/rabbitmq/mnesia
                - ./rabbitMQ/log/:/var/log/rabbit:rw
                - ./rabbitMQ/init.sh:/init.sh
            hostname: rabbitMQ

volumes:
    nginx_log:
    laravel_log:
    symfony_log:
    db:
        driver: local